Repository ladybirdweb/faveo-helpdesk, pull requests merged in 2023-06, with the labels that each got.

#8172 Add huntr.dev to SECURITY.md
  SECURITY.md
Labels: Code Approved

#8171 xss-injection
  app/Http/Controllers/Agent/helpdesk/UserController.php
Labels: Code Approved, Functionality Approved

#8190 getting internal server error if there is no user with mobile number
  app/Http/Controllers/Agent/helpdesk/TicketController.php
Labels: Requires Functionality Review, Code Approved
