Repository ladybirdweb/faveo-helpdesk, pull requests merged in 2023-10, with the labels that each got.

#8237 Apply fixes from StyleCI
  app/Http/Controllers/Auth/AuthController.php
  app/Http/Controllers/Client/helpdesk/UnAuthController.php
Labels: size/M

#8238 Apply fixes from StyleCI
  app/Http/Controllers/Client/helpdesk/UnAuthController.php
Labels: size/XS

#8239 Apply fixes from StyleCI
  app/Http/Controllers/Client/helpdesk/UnAuthController.php
Labels: size/XS

#8241 Apply fixes from StyleCI
  app/Http/Controllers/Client/kb/UserController.php
  app/Http/Requests/kb/ArticleRequest.php
  app/Http/Requests/kb/PageRequest.php
  tests/Unit/ArticleControllerTest.php
  tests/Unit/CategoryControllerTest.php
  tests/Unit/PageControllerTest.php
Labels: size/L

#8243 Apply fixes from StyleCI
  tests/Unit/TicketControllerTest.php
Labels: size/XS

#8244 Apply fixes from StyleCI
  app/Api/v1/TokenAuthController.php
  app/Exceptions/Handler.php
  app/FaveoLog/lang/ar/lang.php
  app/FaveoStorage/lang/ar/lang.php
  app/Helper/Finder.php
  app/Http/Controllers/Admin/helpdesk/SettingsController.php
  app/Http/Controllers/Admin/helpdesk/SettingsController2.php
  app/Http/Controllers/Agent/helpdesk/Filter/FilterControllerOld.php
  app/Http/Controllers/Agent/helpdesk/NotificationController.php
  app/Http/Controllers/Agent/helpdesk/OrganizationController.php
  app/Http/Controllers/Agent/helpdesk/TicketController.php
  app/Http/Controllers/Auth/ForgotPasswordController.php
  app/Http/Controllers/Auth/PasswordController.php
  app/Http/Controllers/Client/helpdesk/GuestController.php
  app/Http/Controllers/Client/helpdesk/UnAuthController.php
  app/Http/Controllers/Common/PhpMailController.php
  app/Http/Middleware/RedirectIfAuthenticated.php
  app/Http/Requests/helpdesk/AgentRequest.php
  app/Http/Requests/helpdesk/ClientRequest.php
  app/Http/Requests/helpdesk/CreateTicketRequest.php
  app/Http/Requests/helpdesk/Job/TaskRequest.php
  app/Http/Requests/helpdesk/ProfileRequest.php
  app/Http/Requests/helpdesk/RegisterRequest.php
  app/Http/Requests/helpdesk/Sys_userRequest.php
  lang/ar/datatables.php
  lang/ar/lang.php
  lang/ar/pagination.php
  lang/ar/passwords.php
  lang/ar/validation.php
  lang/en/lang.php
  routes/web.php
Labels: size/XXL

#8246 Apply fixes from StyleCI
  app/FaveoLog/lang/ar/lang.php
  app/FaveoLog/lang/en/lang.php
  lang/ar/lang.php
  lang/en/lang.php
  lang/ru/lang.php
Labels: size/XXL

#8251 Apply fixes from StyleCI
  app/Http/Controllers/Job/QueueController.php
Labels: size/XS

#8253 Apply fixes from StyleCI
  app/Console/Commands/SetupTestEnv.php
  tests/Unit/RouteTest.php
Labels: size/S

#8255 Apply fixes from StyleCI
  app/Console/Commands/SetupTestEnv.php
Labels: size/XS

#8256 Apply fixes from StyleCI
  app/Console/Commands/SetupTestEnv.php
Labels: size/XS

#8257 Apply fixes from StyleCI
  tests/Unit/RouteTest.php
Labels: size/XS

#8258 Apply fixes from StyleCI
  app/Console/Commands/SetupTestEnv.php
Labels: size/XS

#8260 Apply fixes from StyleCI
  tests/Unit/RouteTest.php
Labels: size/XS

#8261 Apply fixes from StyleCI
  tests/Unit/RouteTest.php
Labels: size/XS

#8262 Apply fixes from StyleCI
  tests/Unit/RouteTest.php
Labels: size/XS

#8242 Issue with Pages Fixed
  app/Http/Controllers/Agent/kb/ArticleController.php
  app/Http/Controllers/Agent/kb/CategoryController.php
  app/Http/Controllers/Agent/kb/PageController.php
  app/Http/Controllers/Agent/kb/SettingsController.php
  app/Http/Controllers/Client/kb/UserController.php
  app/Http/Requests/kb/ArticleRequest.php
  app/Http/Requests/kb/ArticleUpdate.php
  app/Http/Requests/kb/PageRequest.php
  phpunit.xml
  resources/views/themes/default1/agent/kb/pages/create.blade.php
  resources/views/themes/default1/agent/kb/pages/edit.blade.php
  resources/views/themes/default1/client/kb/article-list/show.blade.php
  resources/views/themes/default1/client/layout/client.blade.php
  tests/Unit/ArticleControllerTest.php
  tests/Unit/CategoryControllerTest.php
  tests/Unit/PageControllerTest.php
Labels: Code Approved, QA: Functionality Approved, size/XL, PD: Demo Approved

#8265 Apply fixes from StyleCI
  tests/Unit/TicketControllerTest.php
Labels: size/XS

#8266 Apply fixes from StyleCI
  tests/Unit/ArticleControllerTest.php
  tests/Unit/CategoryControllerTest.php
  tests/Unit/PageControllerTest.php
  tests/Unit/TicketControllerTest.php
Labels: size/L

#8267 Apply fixes from StyleCI
  tests/Unit/ArticleControllerTest.php
Labels: size/S

#8268 Apply fixes from StyleCI
  tests/Unit/PageControllerTest.php
  tests/Unit/TicketControllerTest.php
Labels: size/XS

#8270 Apply fixes from StyleCI
  app/Http/Controllers/Client/helpdesk/UnAuthController.php
Labels: size/M
